### ISSUE TITLE
how do i fix this 

### ISSUE THREAD

**Issue by jcemos57** [alievk/avatarify-python#580] opened 2023-05-03 01:05 UTC
File "afy/cam_fomm.py", line 216, in <module>
    from afy import predictor_local
  File "C:\Users\OwestTechNg\avatarify-python\afy\predictor_local.py", line 4, in <module>
    from modules.keypoint_detector import KPDetector
ModuleNotFoundError: No module named 'modules'

**Comment by JohanAR** [comment] 2023-05-03 06:24
Duplicate of #198

**Closed by JohanAR** 2023-05-03 06:24 UTC
