### ISSUE TITLE
CAM NOT POPING UP 

### ISSUE THREAD

**Issue by Wola-design** [alievk/avatarify-python#493] opened 2023-01-05 07:08 UTC
After putting the run_windows.bat it kept showing an error code instead of the camera to pop up
This what it keep showing.
(avatarify) C: \Users \User \avatarify-python-youtube›run_windows.bat
Traceback (most recent call last):
File "afy/cam_fomm-py", line 6, in <modules import requests
ModuleNotFoundError: No module named 'requests"

**Comment by JohanAR** [comment] 2023-01-05 07:50
Duplicate of #445

**Closed by JohanAR** 2023-01-05 07:50 UTC
Labels: duplicate
