### ISSUE TITLE
cmd stuck on receiving from tcp ...

### ISSUE THREAD

**Issue by Rafiei-tayebe** [alievk/avatarify-python#301] opened 2020-11-09 21:39 UTC
**Describe the bug**

I followed the instructions given on colab server, and  the last instruction does nothing. I've attached the screenshot of my cmd further.
**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux):  windows 10
 - GPU model: 
<!-- Run this commands to get GPU info:
Linux: nvidia-smi -L
Windows (CMD): wmic path win32_VideoController get name
```Name
NVIDIA GeForce MX250
Intel(R) UHD Graphics```
-->
 - Any other relevant information: 
<!-- Include the output of the following commands (please wrap in between triple-back-ticks (```):

On Windows (Miniconda prompt) run:
conda activate avatarify
conda info
```     active environment : avatarify
    active env location : C:\anaconda3\envs\avatarify
            shell level : 2
       user config file : C:\Users\Tayebe Rafiei\.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages : __cuda=10.2
       base environment : C:\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\anaconda3\pkgs
                          C:\Users\Tayebe Rafiei\.conda\pkgs
                          C:\Users\Tayebe Rafiei\AppData\Local\conda\conda\pkgs
       envs directories : C:\anaconda3\envs
                          C:\Users\Tayebe Rafiei\.conda\envs
                          C:\Users\Tayebe Rafiei\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.8.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False```
conda list
```# packages in environment at C:\anaconda3\envs\avatarify:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
blosc                     1.20.1               ha925a31_0    conda-forge
ca-certificates           2020.10.14                    0    anaconda
certifi                   2020.6.20                py37_0    anaconda
cffi                      1.14.3           py37h7a1dbc1_0
chardet                   3.0.4                    pypi_0    pypi
cloudpickle               0.5.3                    pypi_0    pypi
cuda100                   1.0                           0    pytorch
cycler                    0.10.0                   pypi_0    pypi
dask                      0.18.2                   pypi_0    pypi
decorator                 4.3.0                    pypi_0    pypi
face-alignment            1.0.0                    pypi_0    pypi
freetype                  2.10.4               hd328e21_0
git                       2.23.0               h6bb4b03_0    anaconda
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.10                     pypi_0    pypi
imageio                   2.3.0                    pypi_0    pypi
intel-openmp              2019.4                      245
jpeg                      9b                   hb83a4c4_2
kiwisolver                1.0.1                    pypi_0    pypi
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.1.0                h56a325e_1
lz4-c                     1.9.2                hf4a77e7_3
matplotlib                2.2.2                    pypi_0    pypi
mkl                       2018.0.3                      1
mkl_fft                   1.0.6            py37hdbbee80_0
mkl_random                1.0.1            py37h77b88f5_1
msgpack                   1.0.0                    pypi_0    pypi
msgpack-numpy             0.4.5                    pypi_0    pypi
networkx                  2.1                      pypi_0    pypi
ninja                     1.10.1           py37h7ef1ec2_0
numpy                     1.15.0           py37h9fa60d3_0
numpy-base                1.15.0           py37h4a99626_0
olefile                   0.46                     py37_0
opencv-python             4.2.0.34                 pypi_0    pypi
openssl                   1.1.1h               he774522_0    anaconda
pandas                    0.23.4                   pypi_0    pypi
pillow                    6.2.2                    pypi_0    pypi
pip                       20.2.4           py37haa95532_0
pycparser                 2.18                     pypi_0    pypi
pyfakewebcam              0.1.0                    pypi_0    pypi
pygit                     0.1                      pypi_0    pypi
pyparsing                 2.2.0                    pypi_0    pypi
python                    3.7.9                h60c2a47_0
python-blosc              1.7.0            py37he774522_0
python-dateutil           2.7.3                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.0.0           py3.7_cuda100_cudnn7_1  [cuda100]  pytorch
pytz                      2018.5                   pypi_0    pypi
pywavelets                0.5.2                    pypi_0    pypi
pyyaml                    5.1                      pypi_0    pypi
pyzmq                     19.0.0                   pypi_0    pypi
requests                  2.23.0                   pypi_0    pypi
scikit-image              0.14.0                   pypi_0    pypi
scikit-learn              0.19.2                   pypi_0    pypi
scipy                     1.1.0                    pypi_0    pypi
setuptools                50.3.1           py37haa95532_1
six                       1.11.0                   pypi_0    pypi
sqlite                    3.33.0               h2a8f88b_0
tbb                       2020.1               he980bc4_0    conda-forge
tbb4py                    2019.9           py37he980bc4_1    conda-forge
tk                        8.6.10               he774522_0
toolz                     0.9.0                    pypi_0    pypi
torchvision               0.2.1                      py_2    pytorch
tqdm                      4.24.0                   pypi_0    pypi
urllib3                   1.25.11                  pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wheel                     0.35.1                     py_0
wincertstore              0.2                      py37_0
xz                        5.2.5                h62dcd97_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.5                h04227a9_0```
:: Environment info
set | findstr /I "CUDA CONDA Python" | findstr /V "Path"
echo %PATH:;=&echo.%

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. -->
![image](https://user-images.githubusercontent.com/56165755/98599050-9effed00-22f0-11eb-8910-5d077d786027.png)


**Logs**
<!-- Got an Exception? Put entire terminal output in between triple-back-ticks (```). If the output is too long, consider text pasting tools like https://gist.github.com or https://pastebin.com -->
``` [1604957146.775274] Loading Predictor```
```[1604957148.406407] Receiving on port 5557```
```[1604957148.413701] Sending on port 5558```
the third one in logs did not have any outcome.

**Comment by alievk** [comment] 2020-11-12 10:27
Proxy through ngrok is not stable. Give another try. You can also set zone in the Colab nearest to you.

**Comment by fockeRR** [comment] 2020-12-17 09:29
Unfortunately same happens to me. When I switched off firewall and connected via mobile data the result is the same, so the blocked ports are no the issue.

**Comment by ochen1** [comment] 2020-12-17 17:58
Duplicate of #240 ?

**Comment by ochen1** [comment] 2021-02-15 22:49
Solution posted as #369.

**Comment by JohanAR** [comment] 2021-02-17 18:54
Please verify solution is working

**Closed** 2021-07-20 11:49 UTC
Labels: more info needed
