### ISSUE TITLE
When run_windows.bat is finished, the two windows do not pop up. (avatarify does not launch)

### ISSUE THREAD

**Issue by board808** [alievk/avatarify-python#336] opened 2020-12-31 09:00 UTC
**Describe the bug**

**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): 
 - GPU model: 

 - Any other relevant information: 

**Screenshots**

**Logs**

**Comment by alievk** [comment] 2020-12-31 09:03
Do you have Nvidia GPU? We need more information..

**Comment by board808** [comment] 2020-12-31 09:31
Yes, I have an RTX 3080. When I run_windows.bat nothing pops up after I choose my camera. Ex:Avatarify does not launch whilst nothing launches at all. I cannot find avatarify.exe in my directory at all.

**Comment by board808** [comment] 2020-12-31 09:33
The two windows do not pop up after installation and inputting the command run_windows.bat.

**Comment by hshshv** [comment] 2020-12-31 13:49
I have the same problem

**Comment by board808** [comment] 2021-01-01 09:57
Any updates on how to fix it?

**Comment by gabtremblay** [comment] 2021-01-01 19:43
Same problem here. RTX3080, Windows 10. Latest drivers.

**Comment by board808** [comment] 2021-01-01 19:54
Also just to mention, I have windows 10 and all of my latest drivers are installed.

**Comment by sjhill01** [comment] 2021-01-05 14:35
Similar issues here (brand new machine w/RTX3070, latest drivers, latest win10 updates), but after a LOOOOONNNNNG time, it eventually starts. It still doesn't work after that, but that'll be a different issue.

**Comment by board808** [comment] 2021-01-05 17:32
Dang seriously? I was hoping to do some funny stuff with this especially with the RTX 3080 :(

**Comment by chapoogie** [comment] 2021-01-12 22:18
same issue. HALP

**Comment by JohanAR** [comment] 2021-01-13 07:48
Please provide the console output/log from when you try to run Avatarify. Since neither of us have a RTX30xx card we can't reproduce the issue, so we are going to need your help if should have any chance of fixing it.

Unless of course you'd prefer donating a RTX3080 to the project *wink* *wink*

**Comment by alievk** [comment] 2021-01-13 09:03
The problem is that we use old Pytorch version which doesn't support brand new 3080. If we update Pytorch we can break support for older GPUs.

@board808 @hshshv @gabtremblay @sjhill01 @chapoogie Open Miniconda and try these:
1. cd avatarify
2. conda activate avatarify
3. conda install pytorch torchvision cudatoolkit=11.0 -c pytorch
4. run_windows.bat

This will update Pytorch to the latest version and should help in your case.

**Comment by JohanAR** [comment] 2021-01-13 09:12
I think this is also a duplicate of #309

**Comment by board808** [comment] 2021-01-15 00:01
File "C:\Users\John\miniconda3\envs\avatarify\lib\site-packages\torch\__init__.py", line 190, in <module>
    from torch._C import *
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

is what it comes out to when I put run_windows.bat after conda install pytorch torchvision cudatoolkit=11.0 -c pytorch

**Comment by alievk** [comment] 2021-01-15 08:07
This was solved in https://github.com/alievk/avatarify/issues/347. I'm going to commit these fixes into the repository later when they are tested on different machines, but now those who have 30x series GPUs can use these commands. Open Miniconda and run (once):
```
cd avatarify
conda activate avatarify
conda install -y -c conda-forge numpy==1.19.1
pip uninstall scikit-image
conda install -y -c conda-forge scikit-image
git pull origin master
```

Than `run_windows.bat` as usual.

**Comment by JohanAR** [comment] 2021-01-19 14:10
alievk has pushed a commit with updated dependencies, which hopefully fixes issues with RTX 30 series GPUs (#350). Please pull latest master and try again if you were having problems when using these graphics cards.

**Comment by JohanAR** [comment] 2021-03-08 11:05
Assuming the issue was resolved by that commit, since nobody posted here since

**Closed by JohanAR** 2021-03-08 11:05 UTC
Labels: duplicate

**Comment by irexstore** [comment] 2022-08-23 14:28
I use nvidia GTX 1660Ti graphics, the whole process runs smoothly but once I run_windows.bat, both my cam and the avatar cam drags, what can i do?

**Comment by JohanAR** [comment] 2022-08-24 06:25
@irexstore your problem has nothing to do with this issue, i.e. that avatarify-python doesn't run on RTX30xx cards

If you want help, open a new issue for your problem and fill out the template questions

**Comment by budujo** [comment] 2022-11-13 03:43
I use Nvidia RTX 3050, AMD RYZEN 5 5000 series, RAM 16GB. I installed avatarify using the python. I followed the installation tuts without leaving each step but encountered a series of problems after installing it. My camera freezes frequently and each time I choses an avatar it takes me the whole day waited for it to load but it won’t. Please is there anyway you can assist me here and help me out ?
