### ISSUE TITLE
Problems with running on google colab

### ISSUE THREAD

**Issue by ItsWAWGaming** [alievk/avatarify-python#368] opened 2021-02-15 20:59 UTC
**Describe the bug**
When I have set-up the remote gpu/server script on google colab successfully and it says worker running e.t.c all of that, It'll even say on the bottom log test code that worker is initialized and the tunnel is open, yet when I open my miniconda and connect, It takes forever and sometimes wont connect at all and I get no error outputs when doing this. I have my region on the colab notebook set to US which is where I'm located.

**To Reproduce**
Run Avatarify on google colab with all the latest version stuff e.t.c. and once you have the worker started and tunnel opened, just connect to it on miniconda and wait.

**Info (please complete the following information):**
 - OS: Windows
 - GPU model:  Radeon RX 580 Series
Windows (CMD): Not sure what this is here.
-->
 - Any other relevant information: 
Nothing out of the usual, it says everything is working properly on the notebook and miniconda prompt.

**Comment by JohanAR** [comment] 2021-02-15 21:42
The last thing I heard was that google did something which prevented colab being used with Avatarify, but I've never tried colab myself so I don't know the current status of it. See https://github.com/alievk/avatarify/issues/315#issuecomment-750698296 and the linked issues if anyone has provided something usable

**Comment by ochen1** [comment] 2021-02-15 22:34
Possible duplicate of:
 * #240
 * #284
 * #301

**Comment by ochen1** [comment] 2021-02-15 22:49
Solution in #369

**Comment by JohanAR** [comment] 2021-02-17 18:54
Please verify if solution is working

**Comment by JohanAR** [comment] 2021-07-20 09:58
Assuming solution worked since nobody complained :)

**Closed by JohanAR** 2021-07-20 09:58 UTC
Labels: cloud gpu, more info needed

**Comment by Samso9th** [comment] 2022-08-12 23:20
still not working

**Comment by ify7908** [comment] 2023-08-05 00:52
No solution yet
